version: '3'

services:
  cache:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    hostname: redis
    network_mode: bridge
    command: bash -c "redis-server --requirepass $$REDIS_PASS --appendonly yes"
    ports:
      - '6379:6379'
    volumes:
      - ./database/cache/data:/data
    env_file:
      - .env.secret
