version: '3'

services:
  cache:
    image: redis/redis-stack:latest
    container_name: redis
    restart: unless-stopped
    hostname: redis
    network_mode: bridge
    environment:
      - REDIS_ARGS="--appendonly yes"
    ports:
      - '6379:6379'
      - 8001:8001
    volumes:
      - data:$$CACHE_Path
    env_file:
      - .env.secret
volumes:
  data: