version: '3'

services:
  cache:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: unless-stopped
    hostname: redis
    network_mode: bridge
    environment:
      - REDIS_ARGS="--appendonly yes"
    ports:
      - '6379:6379'
      - 8001:8001
#     volumes:
#       - data:/home/tiago/scraper/supplements_scraper/database/cache/data/
#     env_file:
#       - .env.secret
# volumes:
#   data: